library(h2o)
h2o.init(nthreads=48, max_mem_size="500G")
data <- h2o.importFile("/mnt/nfs/zhengda/data/Criteo/day_1.factor", col.types=c("categorical", rep("double", 39)))
start <- Sys.time(); res <- summary(data); end <- Sys.time(); print(end -start)
start <- Sys.time(); res <- h2o.prcomp(data, k=ncol(data), transform="STANDARDIZE", , compute_metrics=FALSE); end <- Sys.time(); print(end - start)
start <- Sys.time(); res <- h2o.kmeans(data, k=10, max_iterations=10, init="Random"); end <- Sys.time(); print(end - start)
start <- Sys.time(); res <- h2o.glm(2:40, 1, data, family="binomial", solver="L_BFGS"); end <- Sys.time(); print(end - start)
start <- Sys.time(); res <- h2o.naiveBayes(2:40, 1, data, compute_metrics=FALSE); end <- Sys.time(); print(end - start)
